### ISSUE TITLE
PM Review: Businesses

### ISSUE THREAD

**Issue by adriennelin** [adriennelin/yelp-clone#16]

**Comment by LochandQuay** [comment]
@adriennelin 

Nice!

Honestly, I only really see one very small tweak for now: 
- You'll need to manually scroll to the top of the page when you click on a business from the index. Otherwise, you'll end up scrolled down as far as you were in the index. 

How are images going to be handled?

**Comment by adriennelin** [comment]
I updated the scrolling.

For images, I was planning to have the three static images per business on the show page.  The reviews themselves would then show any new images attached to a review.

**Comment by LochandQuay** [comment]
@adriennelin 

cool. gonna check this off, but I the only thing I'd like to see is maybe a link at the top of the show that goes back to the browse or index.

**Comment by adriennelin** [comment]
Not as obvious, but clicking on the logo already goes back to the index. Does that work?
