### ISSUE TITLE
PM Review: User Authentication

### ISSUE THREAD

**Issue by adriennelin** [adriennelin/yelp-clone#7]

**Comment by LochandQuay** [comment]
@adriennelin 

Quick thing to get out of the way now and for the future: make sure all your Cloudinary image url's are https, not http.

- missing Demo login
- needs to clear errors (especially problematic with below console error)
- console errors: 
  - signing up with invalid credentials: `TypeError: this.props.errors.map is not a function`

I couldn't create an account. Looks like a `500 Internal Server Error`. Have you set up your Heroku database and migrated?

**Comment by adriennelin** [comment]
Updated the url to point to https.

Also added demo login.

Set up db and migrated.

**Comment by LochandQuay** [comment]
@adriennelin 

Looks good! Just a few small things.

Console errors:
- After clicking Demo Login: `Warning: setState(...): You passed an undefined or null state object; instead, use forceUpdate().`
  - Don't use `forceUpdate()`. It's likely an issue elsewhere that's causing this error. Double check what your local state looks like at every step.

Styling:
- Remove bullet points from lists, and ideally make the errors stand out more

**Comment by LochandQuay** [comment]
@adriennelin 

- Errors look better now but are off center
- Clear Errors on form change (signup <=> login)
- Still seeing this warning after clicking Demo Login: Warning: setState(...): You passed an undefined or null state object; instead, use forceUpdate().
